# Config Server identity
spring.application.name=config-server
server.port=8888

# Read configuration from your GitHub repository
spring.cloud.config.server.git.uri=https://github.com/Asit527/procurement-system.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=config-repo

# Health monitoring
management.endpoints.web.exposure.include=health,info